[package]
name = "c-kzg"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
links = "ckzg"

[dependencies]
hex = "0.4.2"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
blst = "0.3.11"

[build-dependencies]
bindgen = "0.66.1"
cc = "1.0"

